# Format: "pkg_id" "Description" "ON|OFF"

PACKAGE_LIST=(
    "docker"     "Docker Container Engine & Compose    "    "ON"
    "etckeeper"  "Track /etc config with Git           "    "ON"
    "firewalld"  "FirewallD Service & Default Rules    "    "ON"
)
