set -g mouse on

bind-key -n C-S-Left previous-window
bind-key -n C-S-Right next-window

bind-key -n C-M-Up select-pane -U
bind-key -n C-M-Down select-pane -D
bind-key -n C-M-Left select-pane -L
bind-key -n C-M-Right select-pane -R
